<?php
// Deutsche Sprachdatei
return [
    'login' => 'Anmelden',
    'register' => 'Registrieren',
    'username' => 'Benutzername',
    'password' => 'Passwort',
    'password_repeat' => 'Passwort (wiederholen)',
    'invite_code' => 'Einladungscode',
    'logout' => 'Abmelden',
    'dashboard' => 'Übersicht',
    'my_goals' => 'Meine Ziele',
    'admin_panel' => 'Admin-Bereich',
    'no_account' => 'Noch kein Konto? Registrieren',
    'has_account' => 'Bereits ein Konto? Anmelden',
    'login_failed' => 'Falscher Benutzername oder Passwort.',
    'rate_limit_exceeded' => 'Zu viele Versuche. Bitte warten Sie 15 Minuten.',
    'username_taken' => 'Dieser Benutzername ist bereits vergeben.',
    'password_too_short' => 'Das Passwort muss mindestens 6 Zeichen lang sein.',
    'passwords_not_match' => 'Passwörter stimmen nicht überein.',
    'invalid_invite_code' => 'Ungültiger Einladungscode.',
    'register_success' => 'Registrierung erfolgreich! Sie können sich nun anmelden.',
    'weekly_status' => 'Wöchentlicher Status',
    'progress' => 'Fortschritt',
    'leaderboard' => 'Rangliste',
    'weekly_champion' => 'Champion der Woche!',
    'finished' => 'Abgeschlossen',
    'continuing' => 'Fortlaufend',
    'add_goal' => 'Ziel hinzufügen',
    'goal_name' => 'Zielname (z.B.: Seiten, Stunden)',
    'target_amount' => 'Zielmenge',
    'unit' => 'Einheit (z.B.: Seiten)',
    'delete' => 'Löschen',
    'save' => 'Speichern',
    'update_progress' => 'Fortschritt aktualisieren',
    'current_value' => 'Aktueller Wert',
    'reset_weekly' => 'Wöchentlicher Reset (Manuell)',
    'detailed_report' => 'Detaillierter Bericht',
    'members' => 'Mitglieder',
    'generate_message' => 'Nachricht generieren',
    'msg_motivational' => 'Motivierend',
    'msg_funny' => 'Lustig',
    'msg_simple' => 'Einfach',
    'copy_clipboard' => 'Kopieren',
    'copied' => 'Kopiert!',
    'language' => 'Sprache',
    'welcome' => 'Willkommen,',
    'status_done' => 'Geschafft!',
    'msg_tpl_motivational' => 'Was für eine tolle Woche! 🌟 {champion} ist der Champion dieser Woche! {done_count} haben ihr Ziel erreicht, {cont_count} machen weiter. Weiter so!',
    'msg_tpl_funny' => 'Hallo Bücherwürmer! 🐛 {champion} hat uns alle überholt. {done_count} sind fertig, {cont_count} versuchen noch zu lesen. Bleibt stark!',
    'msg_tpl_simple' => 'Wochenbericht: Champion: {champion}. Fertig: {done_count}. Laufend: {cont_count}. Glückwunsch an alle.',
];
?>
