<?php
// Englische Sprachdatei
return [
    'login' => 'Login',
    'register' => 'Register',
    'username' => 'Username',
    'password' => 'Password',
    'password_repeat' => 'Repeat Password',
    'invite_code' => 'Invite Code',
    'logout' => 'Logout',
    'dashboard' => 'Dashboard',
    'my_goals' => 'My Goals',
    'admin_panel' => 'Admin Panel',
    'no_account' => 'No account? Register',
    'has_account' => 'Already have an account? Login',
    'login_failed' => 'Invalid username or password.',
    'rate_limit_exceeded' => 'Too many attempts. Please wait 15 minutes.',
    'username_taken' => 'This username is already taken.',
    'password_too_short' => 'Password must be at least 6 characters.',
    'passwords_not_match' => 'Passwords do not match.',
    'invalid_invite_code' => 'Invalid invite code.',
    'register_success' => 'Registration successful! You can now login.',
    'weekly_status' => 'Weekly Status',
    'progress' => 'Progress',
    'leaderboard' => 'Leaderboard',
    'weekly_champion' => 'Weekly Champion!',
    'finished' => 'Finished',
    'continuing' => 'Continuing',
    'add_goal' => 'Add Goal',
    'goal_name' => 'Goal Name (e.g., Pages, Hours)',
    'target_amount' => 'Target Amount',
    'unit' => 'Unit (e.g., pages)',
    'delete' => 'Delete',
    'save' => 'Save',
    'update_progress' => 'Update Progress',
    'current_value' => 'Current Value',
    'reset_weekly' => 'Weekly Reset (Manual)',
    'detailed_report' => 'Detailed Report',
    'members' => 'Members',
    'generate_message' => 'Generate Message',
    'msg_motivational' => 'Motivational',
    'msg_funny' => 'Funny',
    'msg_simple' => 'Simple',
    'copy_clipboard' => 'Copy',
    'copied' => 'Copied!',
    'language' => 'Language',
    'welcome' => 'Welcome,',
    'status_done' => 'Done!',
    'msg_tpl_motivational' => 'What a great week! 🌟 {champion} is this week\'s champion! {done_count} reached their goal, {cont_count} keep going. Keep it up!',
    'msg_tpl_funny' => 'Hello bookworms! 🐛 {champion} outpaced us all. {done_count} are done, {cont_count} are still trying to read. Stay strong!',
    'msg_tpl_simple' => 'Weekly Report: Champion: {champion}. Finished: {done_count}. Continuing: {cont_count}. Congrats to all.',
];
?>
