<?php
// Türkische Sprachdatei
return [
    'login' => 'Giriş Yap',
    'register' => 'Kayıt Ol',
    'username' => 'Kullanıcı Adı',
    'password' => 'Şifre',
    'password_repeat' => 'Şifre (Tekrar)',
    'invite_code' => 'Davet Kodu',
    'logout' => 'Çıkış Yap',
    'dashboard' => 'Panel',
    'my_goals' => 'Hedeflerim',
    'admin_panel' => 'Yönetici Paneli',
    'no_account' => 'Hesabın yok mu? Kayıt ol',
    'has_account' => 'Zaten hesabın var mı? Giriş yap',
    'login_failed' => 'Hatalı kullanıcı adı veya şifre.',
    'rate_limit_exceeded' => 'Çok fazla deneme yaptınız. Lütfen 15 dakika bekleyin.',
    'username_taken' => 'Bu kullanıcı adı zaten alınmış.',
    'password_too_short' => 'Şifre en az 6 karakter olmalıdır.',
    'passwords_not_match' => 'Şifreler eşleşmiyor.',
    'invalid_invite_code' => 'Geçersiz davet kodu.',
    'register_success' => 'Kayıt başarılı! Şimdi giriş yapabilirsiniz.',
    'weekly_status' => 'Haftalık Durum',
    'progress' => 'İlerleme',
    'leaderboard' => 'Sıralama',
    'weekly_champion' => 'Haftanın Şampiyonu!',
    'finished' => 'Tamamlayanlar',
    'continuing' => 'Devam Edenler',
    'add_goal' => 'Hedef Ekle',
    'goal_name' => 'Hedef Adı (Örn: Sayfa, Saat)',
    'target_amount' => 'Hedef Miktarı',
    'unit' => 'Birim (Örn: sayfa)',
    'delete' => 'Sil',
    'save' => 'Kaydet',
    'update_progress' => 'İlerlemeyi Güncelle',
    'current_value' => 'Mevcut Değer',
    'reset_weekly' => 'Haftalık Sıfırlama (Manuel)',
    'detailed_report' => 'Detaylı Rapor',
    'members' => 'Üyeler',
    'generate_message' => 'Mesaj Oluştur',
    'msg_motivational' => 'Motivasyonlu',
    'msg_funny' => 'Komik',
    'msg_simple' => 'Sade',
    'copy_clipboard' => 'Kopyala',
    'copied' => 'Kopyalandı!',
    'language' => 'Dil',
    'welcome' => 'Hoş Geldin,',
    'status_done' => 'Tamamlandı!',
    'msg_tpl_motivational' => 'Harika bir hafta! 🌟 {champion} bu haftanın şampiyonu! {done_count} kişi hedefine ulaştı, {cont_count} kişi pes etmiyor. Aynen böyle devam!',
    'msg_tpl_funny' => 'Naber kitap kurtları! 🐛 {champion} hepimizi solladı. {done_count} kişi bitirdi, {cont_count} kişi hala okumaya çalışıyor. Gözlerinize kuvvet!',
    'msg_tpl_simple' => 'Haftalık Rapor: Şampiyon: {champion}. Tamamlayanlar: {done_count}. Devam Edenler: {cont_count}. Herkese tebrikler.',
];
?>
